### ISSUE TITLE
Fails to find titles not using # format

### ISSUE THREAD

**Issue by atsepkov** [amaiorano/md-to-toc#1]
Markdown allows underlining or # titles, this seems to ignore the underlined ones:

```
# Header 1

Header 1
--------

## Header 2

Header 2
=======
```

**Comment by amaiorano** [comment]
You're right, I didn't think of that case because I never use it. I'll try and add that to the script. Thanks for reporting!

**Comment by amaiorano** [comment]
Ok, I just implemented support for underlined headers and pushed it to a new branch. Would you mind testing it for me? Here's a direct link to the new version:

https://github.com/amaiorano/md-to-toc/blob/support-underlined-headers/md-to-toc.py

**Comment by amaiorano** [comment]
Merged into master.
